### ISSUE TITLE
request:  bypass specific zones using mqtt

### ISSUE THREAD

**Issue by gdlesage** [rocket4321/nx584mqtt#2]
Would be a nice feature, I don't see that can be done with commands send through home/alarm/set.  Changing a flag for a specific zone, e.g. home/alarm/zone/<number>/bypassed from false to true does not turn on zone bypass in the alarm.  When away sometimes I like to bypass motions if they are giving false motion alarms.  Thanks

**Comment by rocket4321** [comment]
Sounds like a good idea. Publish and subscribe are typically different topics, so perhaps the same topic as alarm status comes, but cmd like 'BYPASS-ZONE,<partition>,<zone>'

What do you think?

May 4, 2021 8:04:29 AM Gene LeSage ***@***.***>:

**Comment by gdlesage** [comment]
Yes exactly what I was thinking of, you need separate topics for cmd and status for each zone, would appreciate if you could pull it off

**Comment by rocket4321** [comment]
It's the same topic for all cmds. Here's the format I ended up with:

'bypass_toggle,<zone>' - Toggle bypass of zone (be sure zone is bypassable!!)

Released in 0.1.13

**Comment by gdlesage** [comment]
works great as described, thanks for the enhancement
